apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Values.frontend.containername }}
        image: {{ .Values.frontend.image }}  
        ports:
        - containerPort: {{ .Values.service.containerport }}
         name: {{ .Values.service.name }}
        env:
          {{ - range .Values.examplemap }}
          - name: {{ .name }}
            value: {{ .value }}
           {{ - end }} 
      
