apiVersion: v1
kind: Service
metadata:
  labels: {{ include "frontend.labels". | nindent 4 }}
  #labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:             
    app: {{ .Values.frontend.containername }}
  ports:
  - name: {{ .Values.service.name }}
    protocol: {{ .values.service.protocol }}
    port: {{ .Values.service.containerport }}       
    targetPort: {{ .Values.service.name }}   
