name: Deploy based on component
on:
    push: 
     paths: 
        - 'backend-complyscan/**'
    workflow_dispatch: 
permissions:
   id-token: write
   contents: read 
env: 
   ECR_REPOSITORY: my-ecr-repository

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
            
     - name: Fetch credentials
       uses: aws-actions/configure-aws-credentials@v1
       id: my-role
       with:
          role-to-assume: ${{secrets.AWS_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: github-OIDC
          role-duration-seconds: 3600
                
     - name: Login to ECR
       id: login-ecr
       run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_USERNAME }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
       
     
     
     - name: installing using helm
       run: |
            #export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
            cd backend-complyscan
            helm upgrade --install COMPLYTRUST ./backend-complyscan
            
            
