name: Deploy based on component
on:
    push: 
     paths: 
        - 'backend-complyscan/**'
permissions:
   id-token: write
   contents: read 
env: 
   ECR_REPOSITORY: my-ecr-repository

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
            
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

           
     - name: Login to ECR
       id: login-ecr
       run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_USERNAME }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
       
     - name: Build Docker image
       run: |
        cd backend-complyscan
        docker build --tag <imagename> .
    
     - name: Push to ECR
       id: ecr
       uses: jwalton/gh-ecr-push@v1
       with:
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-east-1
            local-image: my-image
            image: my-image:dev-${{ github.sha }}
     
     - name: installing using helm
       run: |
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}
            cd backend-complyscan
            helm upgrade --install COMPLYTRUST ./backend-complyscan
            
            
