name: Deploy based on env
on:
  push: 
     branches: [main,dev]
  pull_request:
     branches: [main,dev]

jobs:
  build:
     steps:
     - uses: actions/checkout@v2
     - name: running staging env
       if: ${{push.branches and pull.branches == 'main'}}
         run: chmod +x github.sh
         run: ./github.sh [imagename] [git dockerfile url]
         shell: bash
     - name: running sandbox env
       if: ${{push.branches and pull.branches == 'dev'}}
         run: chmod +x github.sh
         run: ./github.sh [imagename] [git dockerfile url]
         shell: bash
