name: Deploy based on env
on:
    push: 
     branches: 
        - main
permissions:
   id-token: write
   contents: read 

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: actions/checkout@v3
     - name: Get branch name
       id: branch_name
       run: |
        dirname ${{ github.ref }}
        #echo "::set-output name=branch_name::${{ branch }}"
        
       
     - name: Check folder name
       run: |
         #git diff --name-only --diff-filter=ACMR | grep '/$'
         echo "The folder name is $FOLDER_NAME"
            
       
     
