name: Deploy based on env
on:
    push: 
     branches: ["*"]
    pull_request:
     branches: ["*"]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: running staging env
       if: ${{push.branches or pull.branches == 'main'}}
         run:|
          chmod +x github.sh
          ls -ltr
          date
          #./github.sh [imagename] [git dockerfile url]
          
 
