name: Deploy based on env
on:
    push: 
     branches: 
        - main

jobs: 
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     - uses: actions/checkout@v3
     
     - name: giving permissions and running
       #running
       run: |
        chmod +x github.sh
        bash -x github.sh
       shell: bash
     
     - name: DOCKERHUB LOGIN
       with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Docker push
       run: docker push ${{ secrets.DOCKER_USERNAME }}/firstrepo
