name: Deploy based on env
on:
    push: 
     branches: 
        - 'main'

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: giving permissions and running
       if: ${{push.branches == 'main'}}
       run: |
        chmod +x github.sh
        bash -x github.sh
       shell: bash
