name: Deploy based on env
on:
    push: 
     branches: 
        - main
permissions:
   id-token: write
   contents: read 

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
   
    steps:
     - uses: actions/checkout@v3
     - name: branch-name
       id: branch_name
       run: |
        #dirname refs/heads/main
        #branchname = basename refs/heads/main
        #echo "::set-output name=branch_name::${{ github.ref }}"
        echo ":: set-output name=branchname::basename refs/heads/main"
        
       
       env:
        branchname: ${{ steps.branch-name.outputs.branchname-name }}

       
        #my-output-name: ${{ steps.my-step.outputs.my-output-name }}
        
       
     - name: Check folder name
       run: |
         #git diff --name-only --diff-filter=ACMR | grep '/$'
         echo "The folder name is ${{branchname}}"
            
       
     
