name: Deploy based on env
on:
    push: 
     branches: 
        - main

jobs: 
   
  
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     - uses: actions/checkout@v3
     - name: Get branch name
       id: branch_name
       run: echo "::set-output name=branch_name::${{ github.ref }}"
     
     - name: Extract folder name
       run: |
        
        branch_name=${{ steps.branch_name.outputs.branch_name }}
        folder_name=${branch_name##*/}
        echo "Folder name: $folder_name"
     
   #  - name: reading values from shell
    #   run: ./source.sh
     #  shell: bas
          
    
               
          
     - name: Deploy Helm
       uses: aws-actions/configure-aws-credentials@v1
       with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
     - name: adding folder  
       run: |
         mkdir pulical
         # cd $folder_name
         # helm upgrade ${{ secrets.HELM_NAME }} -f values.yaml -f deployment.yaml $folder_name/${{ secrets.HELM_NAME }}

        
        
      
      
