name: Deploy based on env
on:
    push: 
     branches: ["*"]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     
     - name: giving permissions and running
       run: |
         echo $path
         chmod +x github.sh
       shell: bash
