name: Deploy based on env
on:
    push: 
     branches: 
        - main

jobs: 
   
  login:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      token: ${{ steps.ecr.outputs.token }}
    steps:
      
      - name: Get token to login to Amazon ECR
        uses: PhutureCorp/ecr-login-token@v0.8.0
        with:
          registry: 085395249379.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
     - uses: actions/checkout@v3
     - name: Get branch name
       id: branch_name
       run: echo "::set-output name=branch_name::${{ github.ref }}"
     
     - name: Extract folder name
       run: |
        
        branch_name=${{ steps.branch_name.outputs.branch_name }}
        folder_name=${branch_name##*/}
        echo "Folder name: $folder_name"
     
   #  - name: reading values from shell
    #   run: ./source.sh
     #  shell: bas
          
    
               
          
     - name: Deploy Helm
       uses: bitovi/github-actions-deploy-eks-helm@v1.0.0
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        run: |
         mkdir pulical
         # cd $folder_name
         # helm upgrade ${{ secrets.HELM_NAME }} -f values.yaml -f deployment.yaml $folder_name/${{ secrets.HELM_NAME }}

        
        
      
      
