name: Deploy based on env
on:
    push: 
     branches: [main,dev]
    pull_request:
     branches: [main,dev]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: running staging env
       if: ${{push.branches or pull.branches == 'main'}}
         run:|
          chmod +x github.sh
          ./github.sh [imagename] [git dockerfile url]
          bash github.sh
     - name: running sandbox env
       if: ${{push.branches or pull.branches == 'dev'}}
         run:|
           chmod +x github.sh
           ./github.sh [imagename] [git dockerfile url]
           bash github.sh
