name: Deploy based on env
on:
    push: 
     branches: 
        - main
permissions:
   id-token: write
   contents: read 

jobs: 
     
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: actions/checkout@v3
     - name: Get branch name
       id: branch_name
       run: | 
        echo "::set-output name=branch_name::${{ github.ref }}"
        repo_name=$(basename "$GITHUB_REPOSITORY")

 
     - name: Check folder name
       run: |
         git log --name-only
         FOLDER_NAME=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH)
         echo "The folder name is $FOLDER_NAME"
         
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
       with:
          role-to-assume: 
          aws-region: us-east-1
          #testing
          
     - name: Get ECR Login
       run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 085395249379.dkr.ecr.us-east-1.amazonaws.com
