apiVersion: v1
kind: Service
metadata:
  labels: {{ include "helm-charts.labels". | nindent 4 }}
spec:
  selector:
    app: {{ .values.service.name }}
  ports:
  - name: {{ .values.license.containername }}
    protocol: {{ .values.service.protocol }}
    port: {{ .values.service.containerport }}
    targetPort: {{ .values.license.containername }}

